"""
state.py — LangGraph Global State Schema
=========================================
Single TypedDict passed through every node.  Fields are grouped by the
node responsible for populating them.  The `approved_chapters` field uses
LangGraph's operator.add reducer so each APPROVE event appends to the list
without overwriting it.
"""

from typing import TypedDict, List, Dict, Any, Optional, Annotated
import operator


class TextbookSystemState(TypedDict):
    # ── Phase 1 · Core Metadata  (populated by Node 1: Scope Architect) ──────
    subject: str
    grade_level: str
    target_reading_age: int
    pedagogical_style: str          # e.g. Inquiry-based, Direct Instruction
    compliance_standards: List[str] # e.g. Common Core, NGSS, CBSE
    scope_profile: str              # Narrative scope doc generated by Node 1

    # ── Phase 2 · Structural Blueprint  (populated by Node 3: Scaffold) ──────
    table_of_contents: List[Dict[str, Any]]
    # Per-chapter schema:
    # {
    #   "chapter_id": int,
    #   "title": str,
    #   "focus": str,
    #   "prerequisites": List[str],
    #   "outcomes": List[str],
    #   "subsections": List[str],
    #   "status": "pending" | "approved"
    # }
    total_chapters: int

    # ── Iteration Control ─────────────────────────────────────────────────────
    current_chapter_index: int      # 0-based index into table_of_contents
    current_step: str               # questionnaire | scaffolding | gate |
                                    # researching | drafting | reviewing |
                                    # revise | approved | exporting | complete

    # ── Manuscript Accumulator  (auto-appended via operator.add) ─────────────
    # Each APPROVE call returns {"approved_chapters": [text]} which LangGraph
    # concatenates onto this list automatically.
    approved_chapters: Annotated[List[str], operator.add]

    # ── Research Cache  (populated by Node 2 per chapter) ────────────────────
    research_cache: Dict[str, Any]  # key = "chapter_<id>", value = research blob

    # ── Active Working State ──────────────────────────────────────────────────
    active_chapter_draft: Optional[str]
    user_feedback_buffer: Optional[str]     # Revision notes from reviewer
    selected_activity_type: Optional[str]   # Chosen from writer-gate micro-approval

    # ── Export ───────────────────────────────────────────────────────────────
    export_format: str              # "word" | "pdf"
    export_path: Optional[str]      # Absolute path of the final output file
